name: CI
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
      - toaster
    paths:
      - src/**
      - Makefile
      - include/**
      - .github/workflows/make.yml
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - Makefile
      - include/**
      - .github/workflows/make.yml

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        include:
          - os: ubuntu-latest
            name: Ubuntu Latest
          - os: ubuntu-22.04
            name: Ubuntu 22.04
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (UwU buntu)
        run: |
          sudo apt-get update
          sudo apt-get purge -y man-db
          sudo apt-get install -y make clang wget tar gzip mold

      - name: Build project
        run: make all
        timeout-minutes: 10

      - name: Run tests
        run: make run_test
        timeout-minutes: 10
        env:
          CRIT_DEV: 1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-target-${{ matrix.os }}
          path: target
          retention-days: 2
  format_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Norminette
        run: |
          python3 -m pip install norminette --upgrade --user

      - name: Run Norminette
        run: |
          python3 -m norminette --use-gitignore
        continue-on-error: true
        timeout-minutes: 2
