name: CI
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04, macos-latest]
        include:
          - os: ubuntu-latest
            name: Ubuntu Latest
          - os: ubuntu-22.04
            name: Ubuntu 22.04
          - os: ubuntu-20.04
            name: Ubuntu 20.04

          - os: macos-latest
            name: macOS Latest, cause, why not?
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (UwU buntu)
        if: startsWith(runner.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get purge -y man-db
          sudo apt-get install -y make clang wget tar gzip mold

      - name: Install dependencies (macOS)
        if: startsWith(runner.os, 'macos')
        run: |
          brew update
          brew install make llvm mold

      - name: Build project
        run: make all

      - name: Run tests
        run: make run_test
        env:
          CRIT_DEV: 1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-target
          path: target
          retention-days: 2
  format_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Norminette
        run: |
          python3 -m pip install norminette --upgrade --user

      - name: Run Norminette
        run: |
          python3 -m norminette --use-gitignore
        continue-on-error: true
