name: CI
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Norminette
        run: |
          python3 -m pip install norminette --upgrade --user

      - name: Run Norminette
        run: |
          python3 -m norminette --use-gitignore

      - name: Build project
        run: make all

      - name: Run tests
        run: make run_test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-target
          path: target
          retention-days: 2
